config/routes.rb
SampleApp::Application.routes.draw do
  devise_for :users
  devise_scope :user do 
    match '/sessions/user', to: 'devise/sessions#create', via: :post
  end

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]

  resources :swaps, only: [:index, :create, :destroy, :update]

  get 'tags/:tag', to: 'swaps#index', as: :tag
  get 'place/', to: 'swaps#nearby'

  root  'static_pages#home'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

  

end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render partial: 'shared/feed_item', collection: @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>">
  <%= link_to gravatar_for(feed_item.user), feed_item.user %>
  <span class="user">
    <%= link_to feed_item.user.name, feed_item.user %>
  </span>
  <span class="content"><%= feed_item.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(feed_item.created_at) %> ago.
  </span>
  <!-- should be refactored to avoid duplication with _micropost's delete -->
  <% if current_user?(feed_item.user) %>
  	<%= link_to "delete", feed_item, method: :delete,
  																	 data: { confirm: "You sure?" },
  																	 title: feed_item.content %>
  <% end %>
</li>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content,  
    								placeholder: "Compose new micropost..."	 %>
  </div>
  <%= f.submit "Post", class: "btn btn-medium btn-primary" %>
<% end %>

app/views/shared/_search_form.html.erb
<%= search_form_for Swap.search  do |f| %>
	<div class="field">
		<%= f.label :description_cont, "Search Swaps" %>
		<%= f.text_field :description_cont %>
	</div>
	<div class="actions"><%= f.submit "Search", class: "btn btn-medium btn-primary" %></div>

<% end %>

app/views/shared/_stats.html.erb
<!-- when user is nil it does nothing (profile), but when it isn't (home) it sets @user to the current user -->
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.followed_users.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/shared/_swap_form.html.erb
<%= form_for(@swap) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :description, placeholder: "Compose new swap" %>
  </div>

  <div class="field">
  	<%= f.text_field :offer, placeholder: "What you offer" %>
  </div>

  <div class="field">
  	<%= f.text_field :want, placeholder: "What you want" %>
  </div>

  <div class="field">
    <%= f.text_field :place,
                  placeholder: "City, Province, Country" %>
  </div>

  <div class="field">
    <%= f.text_field :tag_list, 
                  placeholder: "Tags (separated by commas)" %>
  </div>
  <%= f.submit "Create", class: "btn btn-medium btn-primary" %>
<% end %>

app/views/shared/_swaps_feed.html.erb
<% if @swaps_feed_items.any? %>
  <ol class="swaps">
    <%= render partial: 'shared/swaps_feed_item', 
    						collection: @swaps_feed_items %>
  </ol>
  <%= will_paginate @swaps_feed_items %>
<% end %>

app/views/shared/_swaps_feed_item.html.erb
<li id="swap<%= swaps_feed_item.id %>">
  <%= link_to gravatar_for(swaps_feed_item.user), swaps_feed_item.user %>
  <span class="user">
    <%= link_to swaps_feed_item.user.name, swaps_feed_item.user %>
  </span>
  <span class="content"><%= swaps_feed_item.description %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(swaps_feed_item.created_at) %> ago.
  </span>
</li>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 70), current_user %>
<h1>
  <%= current_user.name %>
</h1>
<span>
  <%= link_to "view my profile", current_user %>
</span>
<span>
  <%= pluralize(current_user.microposts.count, "micropost") %>
</span>
<span>
	<%= pluralize(current_user.swaps.count, "swap") %>
</span>